# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/MainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(650, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(650, 400))
        mainWindow.setMaximumSize(QtCore.QSize(650, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(388, 12, 256, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.rightColumnLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.rightColumnLayout.setContentsMargins(0, 0, 0, 0)
        self.rightColumnLayout.setObjectName("rightColumnLayout")
        self.secondPlayerOfferDrawBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.secondPlayerOfferDrawBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondPlayerOfferDrawBtn.sizePolicy().hasHeightForWidth())
        self.secondPlayerOfferDrawBtn.setSizePolicy(sizePolicy)
        self.secondPlayerOfferDrawBtn.setObjectName("secondPlayerOfferDrawBtn")
        self.rightColumnLayout.addWidget(self.secondPlayerOfferDrawBtn, 1, 0, 1, 1)
        self.firstPlayerOfferDrawBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.firstPlayerOfferDrawBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstPlayerOfferDrawBtn.sizePolicy().hasHeightForWidth())
        self.firstPlayerOfferDrawBtn.setSizePolicy(sizePolicy)
        self.firstPlayerOfferDrawBtn.setObjectName("firstPlayerOfferDrawBtn")
        self.rightColumnLayout.addWidget(self.firstPlayerOfferDrawBtn, 4, 0, 1, 1)
        self.secondPlayerNickname = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondPlayerNickname.sizePolicy().hasHeightForWidth())
        self.secondPlayerNickname.setSizePolicy(sizePolicy)
        self.secondPlayerNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.secondPlayerNickname.setObjectName("secondPlayerNickname")
        self.rightColumnLayout.addWidget(self.secondPlayerNickname, 0, 0, 1, 1)
        self.firstPlayerNickname = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstPlayerNickname.sizePolicy().hasHeightForWidth())
        self.firstPlayerNickname.setSizePolicy(sizePolicy)
        self.firstPlayerNickname.setAlignment(QtCore.Qt.AlignCenter)
        self.firstPlayerNickname.setObjectName("firstPlayerNickname")
        self.rightColumnLayout.addWidget(self.firstPlayerNickname, 3, 0, 1, 1)
        self.secondPlayerSurrenderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.secondPlayerSurrenderBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondPlayerSurrenderBtn.sizePolicy().hasHeightForWidth())
        self.secondPlayerSurrenderBtn.setSizePolicy(sizePolicy)
        self.secondPlayerSurrenderBtn.setObjectName("secondPlayerSurrenderBtn")
        self.rightColumnLayout.addWidget(self.secondPlayerSurrenderBtn, 1, 1, 1, 1)
        self.firstPlayerSurrenderBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.firstPlayerSurrenderBtn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firstPlayerSurrenderBtn.sizePolicy().hasHeightForWidth())
        self.firstPlayerSurrenderBtn.setSizePolicy(sizePolicy)
        self.firstPlayerSurrenderBtn.setObjectName("firstPlayerSurrenderBtn")
        self.rightColumnLayout.addWidget(self.firstPlayerSurrenderBtn, 4, 1, 1, 1)
        self.movesList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.movesList.setObjectName("movesList")
        self.rightColumnLayout.addWidget(self.movesList, 2, 0, 1, 2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setObjectName("menubar")
        self.actions = QtWidgets.QMenu(self.menubar)
        self.actions.setObjectName("actions")
        mainWindow.setMenuBar(self.menubar)
        self.actionNewGame = QtWidgets.QAction(mainWindow)
        self.actionNewGame.setObjectName("actionNewGame")
        self.actionPVSAI = QtWidgets.QAction(mainWindow)
        self.actionPVSAI.setObjectName("actionPVSAI")
        self.actionSeeStatistics = QtWidgets.QAction(mainWindow)
        self.actionSeeStatistics.setObjectName("actionSeeStatistics")
        self.actionSeePlayersList = QtWidgets.QAction(mainWindow)
        self.actionSeePlayersList.setObjectName("actionSeePlayersList")
        self.actions.addAction(self.actionNewGame)
        self.actions.addSeparator()
        self.actions.addAction(self.actionSeeStatistics)
        self.menubar.addAction(self.actions.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Small Chess"))
        self.secondPlayerOfferDrawBtn.setText(_translate("mainWindow", "Offer a draw"))
        self.firstPlayerOfferDrawBtn.setText(_translate("mainWindow", "Offer a draw"))
        self.secondPlayerNickname.setText(_translate("mainWindow", "Second player"))
        self.firstPlayerNickname.setText(_translate("mainWindow", "First player"))
        self.secondPlayerSurrenderBtn.setText(_translate("mainWindow", "Surrender"))
        self.firstPlayerSurrenderBtn.setText(_translate("mainWindow", "Surrender"))
        self.actions.setTitle(_translate("mainWindow", "Actions"))
        self.actionNewGame.setText(_translate("mainWindow", "New game"))
        self.actionPVSAI.setText(_translate("mainWindow", "Player VS AI"))
        self.actionSeeStatistics.setText(_translate("mainWindow", "See statistics"))
        self.actionSeePlayersList.setText(_translate("mainWindow", "See players list"))
